name: Lottery Analyzer

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
        default: ''
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  lottery-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run lottery analyzer
      env:
        LOTTERY_NUMBER: ${{ secrets.LOTTERY_NUMBER }}
        ANALYSIS_START_DATE: ${{ github.event.inputs.start_date }}
        ANALYSIS_END_DATE: ${{ github.event.inputs.end_date }}
      run: |
        python lottery_analyzer.py
        
    - name: Upload analysis results
      uses: actions/upload-artifact@v3
      with:
        name: lottery-analysis-results
        path: lottery_analysis_*.json 